app = 'webudp'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

# [[services]]
#   protocol = "udp"
#   internal_port = 8080
#   processes = ["app"]
#   ports = { start_port = 1, end_port = 65535 }